name: release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-16.04

    container:
      # https://hub.docker.com/r/lnhcode/sass
      image: lnhcode/sass:1.23.7

    steps:
      - name: git checkout
        uses: actions/checkout@v1

      - name: build
        shell: sh
        run: ./build.sh